
my:
  condition: true
  thread:
    name: myThread
    coreSize: 12
    maxSize: 24

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springTest?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:

      host: localhost
      port: 6379
      # 选择db1
      database: 3
  redis:
    redisson:
      file: classpath:redisson.yaml

  rabbitmq:
    host: localhost
    port: 5672
    username: whai
    password: whai
    publisher-confirm-type: correlated
    # 不可达到 返回给生产者
    # 当启用publisher-returns时，如果发送者发送的消息无法被消费者确认，消息会返回发送者。否则发送者是不知道的
    template:
      mandatory: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: 1
      logic-not-delete-value: 0
  mapper-locations: "classpath:/mapper/**.xml"



# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: cn.whaifree.springdemo.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
server:
  port: 8080
image:
  oss:
    type: minio
    bucket: picgo
    ak: wOSfawBbzug2S3qz9u6W
    sk: CCxIopdXdBRNPloaFV7l8XplKpVLPzjSnMxlKcru
    endpoint: http://42.192.130.83:9000
